title: lesion-mapping
description: Set of tools for mapping lesions in the brain and/or spinal cord.
remote_theme: carlosperate/jekyll-theme-rtd

repo_url: "https://github.com/neuropoly/lesion-mapping"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
